import { HttpException, HttpStatus } from '@nestjs/common';

export enum AppErrorCode {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  ALREADY_APPLIED = 'ALREADY_APPLIED',
  RECRUITING_NOT_FOUND = 'RECRUITING_NOT_FOUND',
  RECRUITING_CLOSED = 'RECRUITING_CLOSED',
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  GROUP_UNAVAILABLE = 'GROUP_UNAVAILABLE',
  GROUP_ACCESS_FORBIDDEN = 'GROUP_ACCESS_FORBIDDEN',
  GROUP_MEMBER_ALREADY_EXISTS = 'GROUP_MEMBER_ALREADY_EXISTS',
  INVALID_MEMBER_ROLE = 'INVALID_MEMBER_ROLE',
  CANNOT_ADD_SELF = 'CANNOT_ADD_SELF',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  MATCH_PLAYER_NOT_FOUND = 'MATCH_PLAYER_NOT_FOUND',
  MATCH_CANDIDATE_NOT_FOUND = 'MATCH_CANDIDATE_NOT_FOUND',
  MATCH_EDIT_NOT_ALLOWED = 'MATCH_EDIT_NOT_ALLOWED',
  MATCH_LOCK_NOT_READY = 'MATCH_LOCK_NOT_READY',
  MATCH_REOPEN_NOT_ALLOWED = 'MATCH_REOPEN_NOT_ALLOWED',
  MATCH_BALANCE_INVALID = 'MATCH_BALANCE_INVALID',
  RESULT_NOT_FOUND = 'RESULT_NOT_FOUND',
  RESULT_SAVE_FORBIDDEN = 'RESULT_SAVE_FORBIDDEN',
  RESULT_VIEW_FORBIDDEN = 'RESULT_VIEW_FORBIDDEN',
  RESULT_CONFIRM_FORBIDDEN = 'RESULT_CONFIRM_FORBIDDEN',
  RESULT_RESOLVE_FORBIDDEN = 'RESULT_RESOLVE_FORBIDDEN',
  RESULT_ALREADY_FINALIZED = 'RESULT_ALREADY_FINALIZED',
  RESULT_INVALID_STATE = 'RESULT_INVALID_STATE',
  REMATCH_INPUT_UNAVAILABLE = 'REMATCH_INPUT_UNAVAILABLE',
}

export class AppException extends HttpException {
  constructor(
    status: HttpStatus,
    code: string,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(
      {
        success: false,
        code,
        message,
        ...(details ? { details } : {}),
      },
      status,
    );
  }
}
