export enum AuthErrorCode {
  ACCOUNT_EXISTS_WITH_APPLE = 'ACCOUNT_EXISTS_WITH_APPLE',
  ACCOUNT_EXISTS_WITH_GOOGLE = 'ACCOUNT_EXISTS_WITH_GOOGLE',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_UNAVAILABLE = 'ACCOUNT_UNAVAILABLE',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  FORBIDDEN_FEATURE = 'FORBIDDEN_FEATURE',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  LEGACY_AUTH_ROUTE_DISABLED = 'LEGACY_AUTH_ROUTE_DISABLED',
  NICKNAME_ALREADY_IN_USE = 'NICKNAME_ALREADY_IN_USE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  PROVIDER_CONFLICT = 'PROVIDER_CONFLICT',
  REQUIRED_TERMS_NOT_AGREED = 'REQUIRED_TERMS_NOT_AGREED',
  SOCIAL_TOKEN_INVALID = 'SOCIAL_TOKEN_INVALID',
  AUTH_PROVIDER_MISMATCH = 'AUTH_PROVIDER_MISMATCH',
  EMAIL_AUTH_DISABLED = 'EMAIL_AUTH_DISABLED',
  PASSWORD_AUTH_DISABLED = 'PASSWORD_AUTH_DISABLED',
  RATE_LIMITED = 'RATE_LIMITED',
  UNKNOWN_AUTH_ERROR = 'UNKNOWN_AUTH_ERROR',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
}

export const AUTH_ERROR_MESSAGES: Record<AuthErrorCode, string> = {
  [AuthErrorCode.ACCOUNT_EXISTS_WITH_APPLE]: 'Account exists with Apple.',
  [AuthErrorCode.ACCOUNT_EXISTS_WITH_GOOGLE]: 'Account exists with Google.',
  [AuthErrorCode.ACCOUNT_NOT_FOUND]: 'Account was not found.',
  [AuthErrorCode.ACCOUNT_UNAVAILABLE]: 'Account is not available.',
  [AuthErrorCode.AUTH_REQUIRED]: 'Authentication is required.',
  [AuthErrorCode.FORBIDDEN_FEATURE]: 'This feature is not available for the current user.',
  [AuthErrorCode.EMAIL_ALREADY_IN_USE]: 'Email is already in use.',
  [AuthErrorCode.INVALID_CREDENTIALS]: 'Credentials are invalid.',
  [AuthErrorCode.INVALID_EMAIL_FORMAT]: 'Email format is invalid.',
  [AuthErrorCode.INVALID_PAYLOAD]: 'Payload is invalid.',
  [AuthErrorCode.INTERNAL_SERVER_ERROR]: 'Internal server error.',
  [AuthErrorCode.LEGACY_AUTH_ROUTE_DISABLED]:
    'Legacy auth route is disabled. Use the documented endpoint.',
  [AuthErrorCode.NICKNAME_ALREADY_IN_USE]: 'Nickname is already in use.',
  [AuthErrorCode.RESOURCE_NOT_FOUND]: 'Requested resource was not found.',
  [AuthErrorCode.PROVIDER_CONFLICT]: 'Authentication provider does not match the account.',
  [AuthErrorCode.REQUIRED_TERMS_NOT_AGREED]:
    'Required terms must be agreed before signup.',
  [AuthErrorCode.WEAK_PASSWORD]: 'Password does not meet the minimum strength requirement.',
  [AuthErrorCode.SOCIAL_TOKEN_INVALID]: 'Social identity token is invalid.',
  [AuthErrorCode.AUTH_PROVIDER_MISMATCH]: 'Authentication provider does not match the account.',
  [AuthErrorCode.EMAIL_AUTH_DISABLED]: 'Email authentication is disabled.',
  [AuthErrorCode.PASSWORD_AUTH_DISABLED]: 'Password authentication is disabled.',
  [AuthErrorCode.RATE_LIMITED]: 'Request rate limit exceeded.',
  [AuthErrorCode.UNKNOWN_AUTH_ERROR]: 'Unknown authentication error.',
};
